### ISSUE TITLE
Error message with no error message inside

### ISSUE THREAD

**Issue by gjorans** [sacredbanana/AmigaGPT#2] opened 2023-06-19 16:01 UTC
I was trying AmigaGPT emulated using bsdsocket.library. Is this not supported? I get a window saying "Error" with nothing inside the error window. Making an issue in case it is a bug.

I installed it on AmigaOS 3.2 with the linked version of AmiSSL and Translator. I did check that networking is indeed working (using aweb to test)
![Screenshot_2023-06-19_17-59-40](https://github.com/sacredbanana/AmigaGPT/assets/6814714/94e0def6-1362-45c2-b30e-b5279621fd54)

**Comment by gjorans** [comment] 2023-06-19 18:37
did some additional testing to better pinpoint the problem. Changed into using roadshow and get the same problem. So my guess is that it is not related to uae as I was now using A2065.

**Comment by sacredbanana** [comment] 2023-06-20 02:41
That is a strange one. I have tested it in UAE (via AmiKit) and it works well. I'll have a look around and try to figure out what's going on though. Thanks for the report.

**Comment by sacredbanana** [comment] 2023-06-20 02:54
If you look in the directory where you have AmigaGPT installed, do you see a file called config.json? It could be an error creating that file.

**Comment by gjorans** [comment] 2023-06-20 10:03
The file is there. I am attaching a screenshot of the content, but it looks to be in good shape to me. My setup is a plain installation of AmigaOS 3.2 with only AmigaGPT + those extras from your install guide (AmiSSL ++).
![Screenshot_2023-06-20_11-58-49](https://github.com/sacredbanana/AmigaGPT/assets/6814714/b4247db1-63fc-46f7-91c0-b976e526bef7)

**Comment by sacredbanana** [comment] 2023-06-20 10:45
Sometimes AmigaGPT will open a new console window to display errors. If you open the app in workbench mode instead of a new screen you'll be able to see the console window if it opens one. Can you let me know if it opened a console window displaying an error?

**Comment by gjorans** [comment] 2023-06-20 11:01
No console window saying anything. 

**However**! I tried deleting the config.json file, restarting it and making a new API-key and with a fresh config file it now works. I have absolutely no idea what happened. Could I have written the wrong api key (even though I checked many times and even tried to create a new one and enter a new one yesterday)? That may very well be what happened. 

I tried putting some random stuff in the api key now and it does give me that same blank error message. So it must be something that went wrong on the human end of it. Sorry if I have waisted your time.

**Comment by sacredbanana** [comment] 2023-06-20 11:03
Awesome! No wasted time! Now you have let me know to properly test bad API keys to make sure it handles errors properly. I'll look into that for the next update!

**Comment by sacredbanana** [comment] 2023-06-20 11:12
I was confused at first because if it was a bsdsocket issue then this would happen:

![image](https://github.com/sacredbanana/AmigaGPT/assets/6903516/c9b3462f-8ab8-4923-9982-35bd9732dae7)

**Comment by sacredbanana** [comment] 2023-06-26 10:23
No matter what I try, I can't seem to ever be able to produce an empty error message

**Comment by sacredbanana** [comment] 2023-11-05 02:29
Been months and unable to reproduce. Closing for now.

**Closed by sacredbanana** 2023-11-05 02:29 UTC
Labels: bug, unable-to-reproduce
