### ISSUE TITLE
Request to Change Encoding from UTF-8 to ISO-8859 for French Language 

### ISSUE THREAD

**Issue by Stephan83c** [sacredbanana/AmigaGPT#4] opened 2023-07-10 08:46 UTC
Hi, 

I am writing to inquire about the possibility of changing the encoding of my GitHub repository from UTF-8 to ISO-8859. The reason behind this request is that I am currently using AmigaGPT, and when I generate responses in French, some characters appear broken or garbled.

By switching the encoding to ISO-8859, which supports the French language more effectively, I believe I can ensure the proper display of accented characters and other language-specific symbols in the responses generated by AmigaGPT.

Is it possible to make the modification?

Stephan.

**Comment by sacredbanana** [comment] 2023-07-10 09:02
Bonjour! UTF-8 does support French. I think the issue is the app may be plain ASCII which does not support French. I will look into seeing if I can make it UTF-8 instead. Merci.

**Comment by sacredbanana** [comment] 2023-07-22 12:11
Fixed in latest release (1.1.0)

**Closed by sacredbanana** 2023-07-22 12:11 UTC
Labels: enhancement

**Comment by sacredbanana** [comment] 2025-03-25 15:05
I was so naive. The reality was that the app was already in ISO-8859-1 but the responses coming back from OpenAI were UTF-8 so the poor Amiga got confused. I had to re-encode all responses to and from OpenAI. Would be great if UTF-8 was supported on Amiga. Imagine being able to use emoji on your Amiga
